# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_place_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WindowEight(object):
    def setupUi(self, WindowEight):
        WindowEight.setObjectName("WindowEight")
        WindowEight.resize(400, 300)
        self.verticalLayoutWidget = QtWidgets.QWidget(WindowEight)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 380, 280))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.textEdit = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout_3.addWidget(self.textEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.btn_8_1 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_8_1.setObjectName("btn_8_1")
        self.verticalLayout.addWidget(self.btn_8_1)

        self.btn_11_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_11_2.setObjectName("btn_11_2")
        self.verticalLayout.addWidget(self.btn_11_2)

        self.retranslateUi(WindowEight)
        QtCore.QMetaObject.connectSlotsByName(WindowEight)

    def retranslateUi(self, WindowEight):
        _translate = QtCore.QCoreApplication.translate
        WindowEight.setWindowTitle(_translate("WindowEight", "Dialog"))
        self.label.setText(_translate("WindowEight", "Добавление заведения"))
        self.label_2.setText(_translate("WindowEight", "Название"))
        self.label_3.setText(_translate("WindowEight", "Тип заведения"))
        self.label_4.setText(_translate("WindowEight", "Описание"))
        self.btn_8_1.setText(_translate("WindowEight", "Добавить"))
        self.btn_11_2.setText(_translate("WindowEight", "Назад"))
