# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_review__window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WindowSeven(object):
    def setupUi(self, WindowSeven):
        WindowSeven.setObjectName("WindowSeven")
        WindowSeven.resize(400, 300)
        self.verticalLayoutWidget = QtWidgets.QWidget(WindowSeven)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(50, 50, 291, 211))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.textEdit = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.btn_7_1 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_7_1.setObjectName("btn_7_1")
        self.verticalLayout.addWidget(self.btn_7_1)

        self.btn_11_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_11_2.setObjectName("btn_11_2")
        self.verticalLayout.addWidget(self.btn_11_2)

        self.retranslateUi(WindowSeven)
        QtCore.QMetaObject.connectSlotsByName(WindowSeven)

    def retranslateUi(self, WindowSeven):
        _translate = QtCore.QCoreApplication.translate
        WindowSeven.setWindowTitle(_translate("WindowSeven", "Dialog"))
        self.label.setText(_translate("WindowSeven", "Новый отзыв"))
        self.btn_7_1.setText(_translate("WindowSeven", "Добавить отзыв"))
        self.btn_11_2.setText(_translate("WindowSeven", "Назад"))
