# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'show_menu_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WindowFour(object):
    def setupUi(self, WindowFour):
        WindowFour.setObjectName("WindowFour")
        WindowFour.resize(400, 300)
        self.verticalLayoutWidget = QtWidgets.QWidget(WindowFour)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 380, 280))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.textBrowser = QtWidgets.QTextBrowser(self.verticalLayoutWidget)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.btn_4_1 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_4_1.setObjectName("btn_4_1")
        self.verticalLayout.addWidget(self.btn_4_1)

        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_5.addWidget(self.comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_5)

        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton")
        self.horizontalLayout_6.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_3.setObjectName("pushButton")
        self.horizontalLayout_6.addWidget(self.pushButton_3)
        self.verticalLayout.addLayout(self.horizontalLayout_6)

        self.btn_4_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_4_2.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.btn_4_2)

        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout")
        self.btn_5 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_5.setObjectName("pushButton")
        self.horizontalLayout_7.addWidget(self.btn_5)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.verticalLayout.addLayout(self.horizontalLayout_7)

        self.retranslateUi(WindowFour)
        QtCore.QMetaObject.connectSlotsByName(WindowFour)

    def retranslateUi(self, WindowFour):
        _translate = QtCore.QCoreApplication.translate
        WindowFour.setWindowTitle(_translate("WindowFour", "Dialog"))
        self.label.setText(_translate("WindowFour", "Меню"))
        self.label_6.setText(_translate("WindowFour", "Выберите:"))
        self.label_7.setText(_translate("WindowFour", "Скидка неактивирована"))
        self.btn_4_1.setText(_translate("WindowFour", "Добавить блюдо"))
        self.btn_4_2.setText(_translate("WindowFour", "Назад"))
        self.btn_5.setText(_translate("WindowFour", "Скидка"))
        self.pushButton_2.setText(_translate("WindowFour", "Удалить"))
        self.pushButton_3.setText(_translate("WindowFour", "Обновить"))
