from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_update_menu(object):
    def setupUi(self, WindowNine):
        WindowNine.setObjectName("WindowNine")
        WindowNine.resize(400, 300)
        self.verticalLayoutWidget = QtWidgets.QWidget(WindowNine)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 380, 280))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.textEdit = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout_3.addWidget(self.textEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_9.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.btn_9_1 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_9_1.setObjectName("btn_9_1")
        self.verticalLayout.addWidget(self.btn_9_1)

        self.btn_11_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_11_2.setObjectName("btn_11_2")
        self.verticalLayout.addWidget(self.btn_11_2)

        self.retranslateUi(WindowNine)
        QtCore.QMetaObject.connectSlotsByName(WindowNine)

    def retranslateUi(self, WindowNine):
        _translate = QtCore.QCoreApplication.translate
        WindowNine.setWindowTitle(_translate("WindowNine", "Dialog"))
        self.label.setText(_translate("WindowNine", "Обновите блюдо"))
        self.label_3.setText(_translate("WindowNine", "Название"))
        self.label_4.setText(_translate("WindowNine", "Описание"))
        self.label_9.setText(_translate("WindowNine", "Цена"))
        self.btn_9_1.setText(_translate("WindowNine", "Сохранить"))
        self.btn_11_2.setText(_translate("WindowNine", "Назад"))
